// Code generated by "bitfanDoc -codec codec"; DO NOT EDIT
package rubydebugcodec

import "github.com/vjeantet/bitfan/processors/doc"

func (p *codec) Doc() *doc.Codec {
	return &doc.Codec{
  Name:       "rubydebugcodec",
  ImportPath: "/Users/sodadi/go/src/github.com/vjeantet/bitfan/codecs/rubydebugcodec",
  Doc:        "",
  DocShort:   "",
  Options:    &doc.CodecOptions{
    Doc:     "",
    Options: []*doc.CodecOption{},
  },
}
}