// Code generated by "bitfanDoc -codec encoder,decoder"; DO NOT EDIT
package rubydebugcodec

import "github.com/vjeantet/bitfan/processors/doc"

func (p *encoder) Doc() *doc.Codec {
	return&doc.Codec{
  Name:       "rubydebugcodec",
  ImportPath: "/Users/sodadi/go/src/github.com/vjeantet/bitfan/codecs/rubydebug",
  Doc:        "",
  DocShort:   "",
  Options:    &doc.CodecOptions{
    Doc:     "",
    Options: []*doc.CodecOption{},
  },
}
}