// Code generated by "bitfanDoc "; DO NOT EDIT
package inputstdout

import "github.com/vjeantet/bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Processor{
  Name:       "inputstdout",
  ImportPath: "github.com/vjeantet/bitfan/processors/input-stdout",
  Doc:        "",
  DocShort:   "Prints events to the standard output",
  Options:    &doc.ProcessorOptions{
    Doc:     "",
    Options: []*doc.ProcessorOption{
      &doc.ProcessorOption{
        Name:           "Codec",
        Alias:          "codec",
        Doc:            "Codec can be one of  \"json\", \"line\", \"pp\" or \"rubydebug\"",
        Required:       false,
        Type:           "codec",
        DefaultValue:   "\"line\"",
        PossibleValues: []string{
          "\"json\"",
          "\"line\"",
          "\"pp\"",
          "\"rubydebug\"",
        },
        ExampleLS: "codec => \"pp\"",
      },
    },
  },
  Ports: []*doc.ProcessorPort{},
}
}