// Code generated by "bitfanDoc "; DO NOT EDIT
package newterm

import "github.com/vjeantet/bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Processor{
  Name:       "newterm",
  ImportPath: "/Users/sodadi/go/src/github.com/vjeantet/bitfan/processors/filter-newterm",
  Doc:        "This processor matches when a new value appears in a field that has never been seen before.",
  DocShort:   "drop event when term was already seen before",
  Options:    &doc.ProcessorOptions{
    Doc:     "",
    Options: []*doc.ProcessorOption{
      &doc.ProcessorOption{
        Name:           "AddField",
        Alias:          "add_field",
        Doc:            "If this filter is successful, add any arbitrary fields to this event.",
        Required:       false,
        Type:           "hash",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "",
      },
      &doc.ProcessorOption{
        Name:           "AddTag",
        Alias:          "add_tag",
        Doc:            "If this filter is successful, add arbitrary tags to the event. Tags can be dynamic\nand include parts of the event using the %{field} syntax.",
        Required:       false,
        Type:           "array",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "",
      },
      &doc.ProcessorOption{
        Name:           "RemoveField",
        Alias:          "remove_field",
        Doc:            "If this filter is successful, remove arbitrary fields from this event. Example:\n` kv {\n`   remove_field => [ \"foo_%{somefield}\" ]\n` }",
        Required:       false,
        Type:           "array",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "",
      },
      &doc.ProcessorOption{
        Name:           "RemoveTag",
        Alias:          "remove_tag",
        Doc:            "If this filter is successful, remove arbitrary tags from the event. Tags can be dynamic and include parts of the event using the %{field} syntax.\nExample:\n` kv {\n`   remove_tag => [ \"foo_%{somefield}\" ]\n` }\nIf the event has field \"somefield\" == \"hello\" this filter, on success, would remove the tag foo_hello if it is present. The second example would remove a sad, unwanted tag as well.",
        Required:       false,
        Type:           "array",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "",
      },
      &doc.ProcessorOption{
        Name:           "CompareField",
        Alias:          "compare_field",
        Doc:            "The name of the field to use to compare to terms list.\nIf the field is null, those events will be ignored.",
        Required:       true,
        Type:           "string",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "compare_field => \"message\"",
      },
      &doc.ProcessorOption{
        Name:           "IgnoreMissing",
        Alias:          "ignore_missing",
        Doc:            "If true, events without a compare_field field will be ignored.",
        Required:       false,
        Type:           "bool",
        DefaultValue:   "true",
        PossibleValues: []string{},
        ExampleLS:      "ignore_missing => true",
      },
      &doc.ProcessorOption{
        Name:           "Terms",
        Alias:          "terms",
        Doc:            "A list of initial terms to consider now new.\nThe compare_field term must be in this list or else it will match.",
        Required:       false,
        Type:           "array",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "terms => [\"val1\",\"val2\",\"val3\"]",
      },
    },
  },
  Ports: []*doc.ProcessorPort{
    &doc.ProcessorPort{
      Default: true,
      Name:    "PORT_SUCCESS",
      Number:  0,
      Doc:     "",
    },
  },
}
}