// Code generated by "bitfanDoc "; DO NOT EDIT
package newterm

import "github.com/awillis/bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Processor{
		Name:       "newterm",
		ImportPath: "github.com/awillis/bitfan/processors/filter-newterm",
		Doc:        "This processor matches when a new value appears in a field that has never been seen before.",
		DocShort:   "drop event when term was already seen before",
		Options: &doc.ProcessorOptions{
			Doc: "",
			Options: []*doc.ProcessorOption{
				&doc.ProcessorOption{
					Name:           "processors.CommonOptions",
					Alias:          ",squash",
					Doc:            "",
					Required:       false,
					Type:           "processors.CommonOptions",
					DefaultValue:   nil,
					PossibleValues: []string{},
					ExampleLS:      "",
				},
				&doc.ProcessorOption{
					Name:           "CompareField",
					Alias:          "compare_field",
					Doc:            "The name of the field to use to compare to terms list.\nIf the field is null, those events will be ignored.",
					Required:       true,
					Type:           "string",
					DefaultValue:   nil,
					PossibleValues: []string{},
					ExampleLS:      "compare_field => \"message\"",
				},
				&doc.ProcessorOption{
					Name:           "IgnoreMissing",
					Alias:          "ignore_missing",
					Doc:            "If true, events without a compare_field field will be ignored.",
					Required:       false,
					Type:           "bool",
					DefaultValue:   "true",
					PossibleValues: []string{},
					ExampleLS:      "ignore_missing => true",
				},
				&doc.ProcessorOption{
					Name:           "Terms",
					Alias:          "terms",
					Doc:            "A list of initial terms to consider now new.\nThe compare_field term must be in this list or else it will match.",
					Required:       false,
					Type:           "array",
					DefaultValue:   nil,
					PossibleValues: []string{},
					ExampleLS:      "terms => [\"val1\",\"val2\",\"val3\"]",
				},
			},
		},
		Ports: []*doc.ProcessorPort{
			&doc.ProcessorPort{
				Default: true,
				Name:    "PORT_SUCCESS",
				Number:  0,
				Doc:     "",
			},
		},
	}
}
