// Code generated by "bitfanDoc -codec line"; DO NOT EDIT
package linecodec

import "github.com/vjeantet/bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Codec{
  Name:       "linecodec",
  ImportPath: "/Users/sodadi/go/src/github.com/vjeantet/bitfan/codecs/line",
  Doc:        "",
  DocShort:   "",
  Options:    &doc.CodecOptions{
    Doc:     "",
    Options: []*doc.CodecOption{
      &doc.CodecOption{
        Name:           "Delimiter",
        Alias:          "",
        Doc:            "Change the delimiter that separates lines",
        Required:       false,
        Type:           "string",
        DefaultValue:   "\"\\\\n\"",
        PossibleValues: []string{},
        ExampleLS:      "",
      },
      &doc.CodecOption{
        Name:           "Format",
        Alias:          "format",
        Doc:            "Format (Encoder) as a golang text/template",
        Required:       false,
        Type:           "string",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "",
      },
      &doc.CodecOption{
        Name:           "Var",
        Alias:          "var",
        Doc:            "You can set variable to be used in Statements by using ${var}.\neach reference will be replaced by the value of the variable found in Statement's content\nThe replacement is case-sensitive.",
        Required:       false,
        Type:           "hash",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "var => {\"hostname\"=>\"myhost\",\"varname\"=>\"varvalue\"}",
      },
    },
  },
}
}