// Code generated by "bitfanDoc -codec lineDecoder"; DO NOT EDIT
package linecodec

import "github.com/vjeantet/bitfan/processors/doc"

func (p *lineDecoder) Doc() *doc.Codec {
	return &doc.Codec{
  Name:       "linecodec",
  ImportPath: "/Users/sodadi/go/src/github.com/vjeantet/bitfan/codecs/linecodec",
  Doc:        "",
  DocShort:   "",
  Options:    &doc.CodecOptions{
    Doc:     "",
    Options: []*doc.CodecOption{
      &doc.CodecOption{
        Name:           "Delimiter",
        Alias:          "",
        Doc:            "Change the delimiter that separates lines",
        Required:       false,
        Type:           "string",
        DefaultValue:   "\"\\\\n\"",
        PossibleValues: []string{},
        ExampleLS:      "",
      },
    },
  },
}
}