// Code generated by "bitfanDoc "; DO NOT EDIT
package httppoller

import "github.com/vjeantet/bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Processor{
  Name:       "httppoller",
  ImportPath: "/Users/sodadi/go/src/github.com/vjeantet/bitfan/processors/input-httppoller",
  Doc:        "HTTPPoller allows you to call an HTTP Endpoint, decode the output of it into an event",
  DocShort:   "",
  Options:    &doc.ProcessorOptions{
    Doc:     "",
    Options: []*doc.ProcessorOption{
      &doc.ProcessorOption{
        Name:           "Method",
        Alias:          "",
        Doc:            "",
        Required:       false,
        Type:           "string",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "",
      },
      &doc.ProcessorOption{
        Name:           "Url",
        Alias:          "",
        Doc:            "",
        Required:       false,
        Type:           "string",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "",
      },
    },
  },
  Ports: []*doc.ProcessorPort{},
}
}