// Code generated by "bitfanDoc "; DO NOT EDIT
package gennumbers

import "github.com/vjeantet/bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Processor{
  Name:       "gennumbers",
  ImportPath: "github.com/vjeantet/bitfan/processors/input-gennumbers",
  Doc:        "",
  DocShort:   "generate a number of event",
  Options:    &doc.ProcessorOptions{
    Doc:     "",
    Options: []*doc.ProcessorOption{
      &doc.ProcessorOption{
        Name:           "processors.CommonOptions",
        Alias:          ",squash",
        Doc:            "",
        Required:       false,
        Type:           "processors.CommonOptions",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "",
      },
      &doc.ProcessorOption{
        Name:           "Count",
        Alias:          "count",
        Doc:            "How many events to generate",
        Required:       false,
        Type:           "int",
        DefaultValue:   "1000000",
        PossibleValues: []string{},
        ExampleLS:      "count => 1000000",
      },
      &doc.ProcessorOption{
        Name:           "Interval",
        Alias:          "interval",
        Doc:            "",
        Required:       false,
        Type:           "interval",
        DefaultValue:   nil,
        PossibleValues: []string{},
        ExampleLS:      "interval => \"10\"",
      },
    },
  },
  Ports: []*doc.ProcessorPort{},
}
}