// Code generated by "bitfanDoc "; DO NOT EDIT
package fileoutput

import "github.com/vjeantet/bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Processor{
  Name:     "fileoutput",
  Doc:      "",
  DocShort: "",
  Options:  &doc.ProcessorOptions{
    Doc:     "",
    Options: []*doc.ProcessorOption{
      &doc.ProcessorOption{
        Name:         "Codec",
        Alias:        "codec",
        Doc:          "",
        Required:     false,
        Type:         "string",
        DefaultValue: nil,
        ExampleLS:    "",
      },
      &doc.ProcessorOption{
        Name:         "CreateIfDeleted",
        Alias:        "create_if_deleted",
        Doc:          "",
        Required:     false,
        Type:         "bool",
        DefaultValue: nil,
        ExampleLS:    "",
      },
      &doc.ProcessorOption{
        Name:         "DirMode",
        Alias:        "dir_mode",
        Doc:          "",
        Required:     false,
        Type:         "os.FileMode",
        DefaultValue: nil,
        ExampleLS:    "",
      },
      &doc.ProcessorOption{
        Name:         "FileMode",
        Alias:        "file_mode",
        Doc:          "",
        Required:     false,
        Type:         "os.FileMode",
        DefaultValue: nil,
        ExampleLS:    "",
      },
      &doc.ProcessorOption{
        Name:         "FlushInterval",
        Alias:        "flush_interval",
        Doc:          "",
        Required:     false,
        Type:         "time.Duration",
        DefaultValue: nil,
        ExampleLS:    "",
      },
      &doc.ProcessorOption{
        Name:         "Path",
        Alias:        "path",
        Doc:          "",
        Required:     true,
        Type:         "string",
        DefaultValue: nil,
        ExampleLS:    "",
      },
    },
  },
  Ports: []*doc.ProcessorPort{},
}
}