// Code generated by "bitfanDoc "; DO NOT EDIT
package imap_input

import "bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Processor{
  Name:       "imap_input",
  ImportPath: "bitfan/processors/input-imap",
  Doc:        "",
  DocShort:   "",
  Options:    (*doc.ProcessorOptions)(nil),
  Ports:      []*doc.ProcessorPort{},
}
}