// Code generated by "bitfanDoc "; DO NOT EDIT
package imap_input

import "github.com/vjeantet/bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Processor{
  Name:     "imap_input",
  Doc:      "",
  DocShort: "",
  Options:  (*doc.ProcessorOptions)(nil),
  Ports:    []*doc.ProcessorPort{},
}
}