// Code generated by "bitfanDoc -codec plain"; DO NOT EDIT
package plaincodec

import "github.com/vjeantet/bitfan/processors/doc"

func Doc() *doc.Codec {
	return &doc.Codec{
  Name:       "plain",
  PkgName:    "plaincodec",
  ImportPath: "/Users/sodadi/go/src/github.com/vjeantet/bitfan/codecs/plain",
  Doc:        "",
  DocShort:   "",
  Decoder:    &doc.Decoder{
    Doc:     "",
    Options: &doc.CodecOptions{
      Doc:     "",
      Options: []*doc.CodecOption{},
    },
  },
  Encoder: (*doc.Encoder)(nil),
}
}