// Code generated by "bitfanDoc -codec json"; DO NOT EDIT
package jsoncodec

import "github.com/vjeantet/bitfan/processors/doc"

func (p *processor) Doc() *doc.Processor {
	return &doc.Codec{
  Name:       "jsoncodec",
  ImportPath: "/Users/sodadi/go/src/github.com/vjeantet/bitfan/codecs/json",
  Doc:        "",
  DocShort:   "",
  Options:    &doc.CodecOptions{
    Doc:     "",
    Options: []*doc.CodecOption{
      &doc.CodecOption{
        Name:           "Indent",
        Alias:          "indent",
        Doc:            "Set indentation",
        Required:       false,
        Type:           "string",
        DefaultValue:   "\"\"",
        PossibleValues: []string{},
        ExampleLS:      "indent => \"    \"",
      },
    },
  },
}
}