// Code generated by "bitfanDoc -codec json"; DO NOT EDIT
package jsoncodec

import "github.com/vjeantet/bitfan/processors/doc"

func Doc() *doc.Codec {
	return &doc.Codec{
  Name:       "json",
  PkgName:    "jsoncodec",
  ImportPath: "/Users/sodadi/go/src/github.com/vjeantet/bitfan/codecs/json",
  Doc:        "",
  DocShort:   "",
  Decoder:    &doc.Decoder{
    Doc:     "",
    Options: &doc.CodecOptions{
      Doc:     "",
      Options: []*doc.CodecOption{
        &doc.CodecOption{
          Name:           "Indent",
          Alias:          "indent",
          Doc:            "Set indentation",
          Required:       false,
          Type:           "string",
          DefaultValue:   "\"\"",
          PossibleValues: []string{},
          ExampleLS:      "indent => \"    \"",
        },
      },
    },
  },
  Encoder: &doc.Encoder{
    Doc:     "",
    Options: &doc.CodecOptions{
      Doc:     "",
      Options: []*doc.CodecOption{
        &doc.CodecOption{
          Name:           "Indent",
          Alias:          "indent",
          Doc:            "Set indentation",
          Required:       false,
          Type:           "string",
          DefaultValue:   "\"\"",
          PossibleValues: []string{},
          ExampleLS:      "indent => \"    \"",
        },
      },
    },
  },
}
}